swagger: "2.0"
info:
  version: "1.0.0"
  title: "B5IT Final Project Clinic Application APIs"
  description: "B5IT Final Project Clinic Application APIs."
host: "127.0.0.1:9409"
schemes:
  - "http"
tags:
  - name: "employees"
    description: "all about apis of employees."
  - name: "patients-reservations"
    description: "all about apis of patients-reservations."
paths:
  /api/v1/employees:
    get:
      tags:
        - "employees"
      summary: "find all employees."
      description: "find all employees."
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
    post:
      tags:
        - "employees"
      summary: "create new employee."
      description: "create new employee."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "employeeRequest"
          description: "employee data"
          required: true
          schema:
            $ref: "#/definitions/CreateEmployeeDto"
      responses:
        200:
          description: "Success"

  /api/v1/employees/{id}:
    put:
      tags:
        - "employees"
      summary: "update employee."
      description: "update employee."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "the employee id."
          required: true
          type: "string"
        - in: "body"
          name: "employeeRequest"
          description: "employees data"
          required: true
          schema:
            $ref: "#/definitions/UpdateEmployeeDto"
      responses:
        200:
          description: "Success"
    delete:
      tags:
        - "employees"
      summary: "delete employee."
      description: "delete employee."
      parameters:
        - in: "path"
          name: "id"
          description: "the employee id."
          required: true
          type: "string"
      responses:
        200:
          description: "Success"

  /api/v1/patients-reservations:
    get:
      tags:
        - "patients-reservations"
      summary: "find all patients-reservations."
      description: "find all patients-reservations."
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
    post:
      tags:
        - "patients-reservations"
      summary: "create new patient-reservation."
      description: "create new patient-reservation."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "patientReservationRequest"
          description: "patient reservation data"
          required: true
          schema:
            $ref: "#/definitions/CreatePatientReservationDto"
      responses:
        200:
          description: "Success"

definitions:
  UpdateEmployeeDto:
    type: "object"
    properties:
      fullName:
        type: "string"
        example: "sahar omar ali"
      gender:
        type: "string"
        example: "FEMALE"
      username:
        type: "string"
        example: "soa5"
      password:
        type: "string"
        example: "12345"
      phone:
        type: "string"
        example: "777666555"
      role:
        type: "string"
        example: "RECEPTIONIST"

  CreateEmployeeDto:
    type: "object"
    properties:
      fullName:
        type: "string"
        example: "sahar omar ali"
      gender:
        type: "string"
        example: "FEMALE"
      username:
        type: "string"
        example: "soa5"
      password:
        type: "string"
        example: "12345"
      phone:
        type: "string"
        example: "777666555"
      role:
        type: "string"
        example: "RECEPTIONIST"

  CreatePatientReservationDto:
    type: "object"
    properties:
      fullName:
        type: "string"
        example: "anwar ahmed ali"
      gender:
        type: "string"
        example: "FEMALE"
      email:
        type: "string"
        example: "anwar@gmail.com"
      phone:
        type: "string"
        example: "777666555"
      feeling:
        type: "string"
        example: "she is very sick."
      employeeId:
        type: "string"
        example: "1"